This should have been part of changeset:5069.
(The Common Larceny REPL was broken by the prior default, ERR5RS,
where attempts to start just the bootstrap heap interactively 
yielding: 

{{{
Error: Reference to undefined global variable "primitives".
}}}

or rather, to be complete:

{{{
WARNING from macro expander:
Syntactic keyword used as a variable
begin
WARNING from macro expander:
Syntactic keyword used as a variable
if
WARNING from macro expander:
Syntactic keyword used as a variable
lambda
WARNING from macro expander:
Syntactic keyword used as a variable
quote
WARNING from macro expander:
Syntactic keyword used as a variable
set!
WARNING from macro expander:
Syntactic keyword used as a variable
and
WARNING from macro expander:
Syntactic keyword used as a variable
or
WARNING from macro expander:
Syntactic keyword used as a variable
define
WARNING from macro expander:
Syntactic keyword used as a variable
define-syntax
WARNING from macro expander:
Syntactic keyword used as a variable
let-syntax
WARNING from macro expander:
Syntactic keyword used as a variable
letrec-syntax
WARNING from macro expander:
Syntactic keyword used as a variable
begin
WARNING from macro expander:
Syntactic keyword used as a variable
if
WARNING from macro expander:
Syntactic keyword used as a variable
set!
WARNING from macro expander:
Syntactic keyword used as a variable
and
WARNING from macro expander:
Syntactic keyword used as a variable
or
WARNING from macro expander:
Syntactic keyword used as a variable
lambda
WARNING from macro expander:
Syntactic keyword used as a variable
quote
WARNING from macro expander:
Syntactic keyword used as a variable
define
WARNING from macro expander:
Syntactic keyword used as a variable
define-syntax
WARNING from macro expander:
Syntactic keyword used as a variable
let-syntax
WARNING from macro expander:
Syntactic keyword used as a variable
letrec-syntax

Error: Reference to undefined global variable "primitives".
}}}


git-svn-id: https://trac.ccs.neu.edu/svn/larceny/trunk/larceny_src@5083 c9681fa6-b8ae-40c0-a6da-707a35ad5973