Added check that parameter is an enum set before attempting to apply {{{enum-set-subset?}}} to it.
I made this change because Larceny's current error message when you misapply
{{{enum-set-subset?}}} is pretty terrible:

{{{
Larceny v0.97a3 (alpha test) (Feb  4 2009 10:45:58, precise:Posix Unix:unified)
larceny.heap, built on Wed Feb  4 10:47:27 EST 2009

> (let* ((rgb (make-enumeration '(red green blue)))) (enum-set-subset? 666 rgb))


Error: flfloor: 666 is not a flonum.
Entering debugger; type "?" for help.
debug>
}}}

and right now some of my testbed FFI code is mistakenly passing an
integer where an enum set is expected, so I want the error message to
be clearer about that (and perhaps provide more useful context).


git-svn-id: https://trac.ccs.neu.edu/svn/larceny/trunk/larceny_src@6028 c9681fa6-b8ae-40c0-a6da-707a35ad5973